version: "3.9"

networks:
  apps:

services:
  rabbit-server:
    image: rabbitmq:3.11
    restart: always
    ports:
      - "5672:5672"
    networks:
      - apps

  consumer:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-consumer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - apps

  producer:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-producer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - apps


