# syntax=docker/dockerfile:1

FROM maven:3.8.6-openjdk-18 as maven

COPY --chown=maven:maven . /app

WORKDIR /app

RUN mvn clean package

FROM maven:3.8.6-eclipse-temurin-18-alpine

EXPOSE 8082

WORKDIR /app

COPY --from=maven /app/consumer/target/consumer-1.0-SNAPSHOT.jar /app/consumer-1.0-SNAPSHOT.jar

CMD ["java", "-jar", "/app/consumer-1.0-SNAPSHOT.jar"]